# Generated by Django 4.0.4 on 2022-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(),
        ),
    ]
